### ISSUE TITLE
Needs explanation of stack

### ISSUE THREAD

**Issue by pardeike** [ShoosGun/TranspilerHandbook#1]
I really appreciate this detailed approach to transpiling. There is just one thing you assumed obvious but that really needs some explanation: the stack nature of IL. It would be great to give some simple->advanced examples of stack usage before you dive into the chapters where you actually need to understand it.

**Comment by loco-choco** [comment]
Thanks for the suggestion! Added it on the [The Stack Nature of IL](https://github.com/ShoosGun/TranspilerHandbook/blob/main/transpiler.md#the-stack-nature-of-il) section.
